export const GET_BOOKS_LOADING ="GET_BOOKS_LOADING"
export const GET_BOOKS_SUCESS ="GET_BOOKS_SUCESS"
export const GET_BOOKS_FAILURE ="GET_BOOKS_FAILURE"

export const PATCH_BOOK_LOADING ="PATCH_BOOK_LOADING"
export const PATCH_BOOK_SUCESS ="PATCH_BOOK_SUCESS"
export const PATCH_BOOK_FAILURE ="PATCH_BOOK_FAILURE"