export const HOTEL_REQUEST = "HOTEL_REQUEST";
export const HOTEL_SUCCESS = "HOTEL_SUCCESS";
export const HOTEL_FAILURE = "HOTEL_FAILURE";

export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_SUCCESS = "PLACES_SUCCESS";
export const PLACES_FAILURE = "PLACES_FAILURE";

export const RESTAURANTS_REQUEST = "RESTAURANTS_REQUEST";
export const RESTAURANTS_SUCCESS = "RESTAURANTS_SUCCESS";
export const RESTAURANTS_FAILURE = "RESTAURANTS_FAILURE";

export const SIGHT_REQUEST = "SIGHT_REQUEST";
export const SIGHT_SUCCESS = "SIGHT_SUCCESS";
export const SIGHT_FAILURE = "SIGHT_FAILURE";

// export const ADD_TO_BASKET_REQUEST = "ADD_TO_BASKET_REQUEST";
// export const ADD_TO_BASKET_SUCCESS = "ADD_TO_BASKET_SUCCESS";
// export const ADD_TO_BASKET_FAILURE = "ADD_TO_BASKET_FAILURE";

export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";

export const CART_REQUEST = "CART_REQUEST";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAILURE = "CART_FAILURE";

export const REMOVE_FROM_BASKET_REQUEST = "REMOVE_FROM_BASKET_REQUEST";
export const REMOVE_FROM_BASKET_SUCCESS = "REMOVE_FROM_BASKET_SUCCESS";
export const REMOVE_FROM_BASKET_FAILURE = "REMOVE_FROM_BASKET_FAILURE";

export const CART_ITEMS_LOADING ="CART_ITEMS_LOADING"
export const CART_ITEMS_SUCESS ="CART_ITEMS_SUCESS"
export const CART_ITEMS_FAILURE ="CART_ITEMS_FAILURE"
