export const HOTEL_REQUEST = "HOTEL_REQUEST";
export const HOTEL_SUCCESS = "HOTEL_SUCCESS";
export const HOTEL_FAILURE = "HOTEL_FAILURE";

export const PLACES_REQUEST = "PLACES_REQUEST";
export const PLACES_SUCCESS = "PLACES_SUCCESS";
export const PLACES_FAILURE = "PLACES_FAILURE";

export const RESTAURANTS_REQUEST = "RESTAURANTS_REQUEST";
export const RESTAURANTS_SUCCESS = "RESTAURANTS_SUCCESS";
export const RESTAURANTS_FAILURE = "RESTAURANTS_FAILURE";

export const SIGHT_REQUEST = "SIGHT_REQUEST";
export const SIGHT_SUCCESS = "SIGHT_SUCCESS";
export const SIGHT_FAILURE = "SIGHT_FAILURE";